name: Releases

on: 
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'application-title-bar.plasmoid'
        directory: 'package'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "package/application-title-bar.plasmoid"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
